name: OWASP Noir Endpoint Discovery

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: read   # required for GHCR

jobs:
  noir-scan:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/owasp-noir/noir:v0.26.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run OWASP Noir scan
        run: |
          noir -b ./src/WebGoat -f json > reports/noir-report.json

      - name: Upload Noir Report
        uses: actions/upload-artifact@v4
        with:
          name: noir-report
          path: reports/noir-report.json
